server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # 本机虚拟机
    url: jdbc:mysql://192.168.124.110:3306/edu_ad?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT
    username: root
    password: admin
  klock:
    address: 8.140.107.222:6379
  rabbitmq:
    host: 192.168.124.157
    port: 5672
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    #启用shutdown端点，以便支持优雅停机
    shutdown:
      enabled: true

#分布式链路追踪--调整SpringBoot日志输出级别
logging:
  config: classpath:logback.xml
